name: Swift

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    strategy:
      matrix:
        os: [macos-14, ubuntu-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: SwiftyLab/setup-swift@latest
      with:
        swift-version: ${{ matrix.os == 'windows-latest' && '6.1-dev' || 'latest' }}
        development: ${{ matrix.os == 'windows-latest' }}
    - uses: actions/checkout@v4
      with:
        submodules: true
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test -v
